spring:
  application:
    name: fast-order-manager
  output:
    ansi:
      enabled: always
  datasource:
    platform: h2
    url: "jdbc:h2:mem:fastordermanager;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false"
    username: sa
    password:
#    platform: mysql
#    url: "jdbc:mysql://db:3306/fom"
#    username: root
#    password: example
#    platform: oracle
#    url: "jdbc:oracle:thin:@//db-oracle:1521/XE"
#    username: system
#    password: manager
 
  jpa:
    generate-ddl: true
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: update
   # database-platform: org.hibernate.dialect.Oracle10gDialect
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
    
  data:
    rest:
      enable-enum-translation: true
      
  h2:
    console:
      enabled: true
      path: "/h2-console"
      settings:
        web-allow-others: true

server:
  port: 8080
  
logging:
  level:
    root: 'INFO'
    org.hibernate.SQL: DEBUG
